# openosint/pdf_report.py
"""
PDF report generator for OpenOSINT investigation results.

Converts a Markdown investigation report to a PDF alongside it.
Uses reportlab — falls back silently if not installed.
"""

from __future__ import annotations

import asyncio
import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

_LOGO_TEXT = "OPENOSINT"
_FOOTER_TEXT = "Generated by OpenOSINT — For authorized use only"


def _generate_pdf_sync(md_path: Path, pdf_path: Path, date_str: str) -> None:
    """Blocking PDF generation — intended to run in a thread executor."""
    try:
        from reportlab.lib import colors  # type: ignore
        from reportlab.lib.enums import TA_CENTER  # type: ignore
        from reportlab.lib.pagesizes import A4  # type: ignore
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet  # type: ignore
        from reportlab.lib.units import mm  # type: ignore
        from reportlab.platypus import (  # type: ignore
            HRFlowable,
            Paragraph,
            SimpleDocTemplate,
            Spacer,
        )
    except ImportError:
        logger.warning(
            "reportlab not installed — PDF generation skipped. "
            "Install with: pip install reportlab"
        )
        return

    content = md_path.read_text(encoding="utf-8")
    page_width, page_height = A4

    doc = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=25 * mm,
        bottomMargin=25 * mm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "OsiTitle",
        parent=styles["Heading1"],
        fontSize=18,
        textColor=colors.HexColor("#00cc66"),
        alignment=TA_CENTER,
        spaceAfter=4,
    )
    date_style = ParagraphStyle(
        "OsiDate",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.grey,
        alignment=TA_CENTER,
        spaceAfter=12,
    )
    h1_style = ParagraphStyle(
        "OsiH1",
        parent=styles["Heading1"],
        fontSize=14,
        textColor=colors.HexColor("#1a1a2e"),
        spaceBefore=12,
        spaceAfter=4,
    )
    h2_style = ParagraphStyle(
        "OsiH2",
        parent=styles["Heading2"],
        fontSize=11,
        textColor=colors.HexColor("#1a1a2e"),
        spaceBefore=10,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "OsiBody",
        parent=styles["Normal"],
        fontSize=9,
        leading=14,
        spaceAfter=3,
    )
    mono_style = ParagraphStyle(
        "OsiMono",
        parent=styles["Code"],
        fontSize=8,
        leading=12,
        fontName="Courier",
        spaceAfter=2,
        leftIndent=10,
    )

    story = []

    # Header block
    story.append(Paragraph(_LOGO_TEXT, title_style))
    story.append(Paragraph(f"Investigation Report — {date_str}", date_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
    story.append(Spacer(1, 6 * mm))

    # Body — simple Markdown pass
    in_code_block = False
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith("```"):
            in_code_block = not in_code_block
            continue
        if in_code_block or stripped.startswith("[+]") or stripped.startswith("[*]"):
            safe = stripped.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(safe, mono_style))
        elif stripped.startswith("# ") and not stripped.startswith("## "):
            story.append(Paragraph(stripped[2:], h1_style))
        elif stripped.startswith("## "):
            story.append(Paragraph(stripped[3:], h2_style))
        elif stripped.startswith("**") or stripped:
            safe = stripped.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(safe, body_style))
        else:
            story.append(Spacer(1, 3 * mm))

    def _footer(canvas, doc):  # noqa: ANN001
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.grey)
        canvas.drawCentredString(
            page_width / 2,
            12 * mm,
            f"{_FOOTER_TEXT}   —   Page {doc.page}",
        )
        canvas.restoreState()

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    logger.info("PDF report written: %s", pdf_path)


async def generate_pdf_report(md_path: Path) -> Path | None:
    """
    Asynchronously generate a PDF alongside *md_path*.

    Runs reportlab in a thread executor so the asyncio event loop
    is not blocked.

    Returns
    -------
    Path | None
        Path to the generated PDF on success, ``None`` if skipped or failed.
    """
    pdf_path = md_path.with_suffix(".pdf")
    date_str = datetime.now().strftime("%Y-%m-%d")
    loop = asyncio.get_event_loop()
    try:
        await loop.run_in_executor(None, _generate_pdf_sync, md_path, pdf_path, date_str)
        return pdf_path if pdf_path.exists() else None
    except Exception:
        logger.exception("PDF generation failed for %s.", md_path)
        return None
